### ISSUE TITLE
bug: whitespace is registered as part of name

### ISSUE THREAD

**Issue by gskang-22** [AY2425S1-CS2113-W13-1/tp#129]
![image](https://github.com/user-attachments/assets/e55a8b89-3f9a-4635-991f-a7a99ac6ac28)

When name of ingredient has whitespaces around it, it is not trimmed. Possible use of trim() function to solve the issue. (Problem probably applies to Recipe and its componenents as well)

**Comment by Sukkaito** [comment]
Nice catch, working on it! I'll have to ensure other elements won't allow trailing or leading spaces like these before initializing the recipes and ingredients.
