### ISSUE TITLE
[PE-D][Tester C] No ingredients save file is created

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W13-1/tp#169]
Upon the addition of new recipes or `bye`, no savefile regarding the ingredients is created, despite there being an error message suggesting that the application looks for a save file to load.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: averageandyyy/ped#6

**Comment by Sukkaito** [comment]
Resolved with #215
