### ISSUE TITLE
[PE-D][Tester C] Invalid arrow scheme compared to textbook

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W13-1/tp#188]
According to the texbook, a closed/full arrow is used but the open arrow is used in the DG.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: averageandyyy/ped#11

**Comment by Sukkaito** [comment]
Not enough information provided. Please try again with a more detailed bug report so we can resolve the issue ASAP. Thank you for your time! 👍
