### ISSUE TITLE
[PE-D][Tester E] find [OPTIONS/]KEYWORDS command shouldn't work when only part of the keyword is used

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W13-1/tp#197]
e.g. in my recipe list I have nothing called "te", but when I do find ni/te I am shown all the recipes that have "te" as part of a word

Ingredient list has nothing called "te"
![Screenshot 2024-11-08 at 5.23.57 PM.png](https://raw.githubusercontent.com/naveen42x/ped/main/files/db291521-414b-4db0-9469-30f0c6714d5a.png)

But find ni/te shows:
![Screenshot 2024-11-08 at 5.24.41 PM.png](https://raw.githubusercontent.com/naveen42x/ped/main/files/4b655208-1b35-42f8-ac15-80c552f8f459.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: naveen42x/ped#7

**Comment by Sukkaito** [comment]
This is an intended feature. There will be no fix for this. Thank you for your opinion! 👍

**Comment by Sukkaito** [comment]
This is an intended feature. There will be no fix for this. Thank you for your opinion! 👍

**Comment by Sukkaito** [comment]
This is an intended feature. There will be no fix for this. Thank you for your opinion! 👍
