### ISSUE TITLE
[PE-D][Tester B] `deleteI` command gives mismatching output

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W13-1/tp#199]
The list of ingredients I have:
```
        Here's all the ingredients you currently have:
        1. tom
        2. 1
        3. 12 eggs
        4. 30 eggs
```

Command used:
```
deleteI    n/12 eggs
```

Actual output:
```
        __________________________________________________________________________________
        Aww, I shall begrudgingly let go of this recipe:
          12 eggs
        You currently have 15 recipes in your list.
        __________________________________________________________________________________
```

The program gives statistics for `recipe inventory` instead of `ingredients inventory`, despite correctly delete the ingredient from the inventory (We know this by doing `listI` afterwards). Maybe a small fix would make the output clearer for user.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Metanyu/ped#7

**Comment by Sukkaito** [comment]
Duplicate with #193
