### ISSUE TITLE
[PE-D][Tester C] General: Generic error messages provided

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W13-1/tp#200]
In general, when an invalid command is provided, a generic error message which simply repeats the user's input is provided, which can make it difficult for the user to trouble shoot where or what they are doing wrong. It might be better to provided targetted messages at correcting the user's mistakes, such as having repeated arguments.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: averageandyyy/ped#16

**Comment by Sukkaito** [comment]
Duplicate with #166

**Comment by Sukkaito** [comment]
For now, we have decided that we don't have any plans to support this improvement. There will be no updates on this. Thank you for your opinion! 👍
