### ISSUE TITLE
[PE-D][Tester E] find should work only when entire keyword is spelled out

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W13-1/tp#202]
find should not work when only part of the keyword is spelled.
My recipe list:
![Screenshot 2024-11-08 at 5.32.13 PM.png](https://raw.githubusercontent.com/naveen42x/ped/main/files/221dde41-32d3-4a82-af6d-89f1948633d6.png)

half spelled out keywords still show recipes:
![Screenshot 2024-11-08 at 5.33.24 PM.png](https://raw.githubusercontent.com/naveen42x/ped/main/files/a6e072b5-3ae8-4b55-9cf0-482d51b3eeb1.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: naveen42x/ped#8

**Comment by Sukkaito** [comment]
This is an intended feature. There will be no fix for this. Thank you for your opinion! 👍

**Comment by Sukkaito** [comment]
This is an intended feature. There will be no fix for this. Thank you for your opinion! 👍
