### ISSUE TITLE
[PE-D][Tester E] findI should work only when entire keyword is spelled out

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W13-1/tp#204]
findI should work only when entire keyword is spelled out, and should give an error message when only part of the keyword is spelled.
![Screenshot 2024-11-08 at 5.40.51 PM.png](https://raw.githubusercontent.com/naveen42x/ped/main/files/3242b64f-f044-4467-ad19-7032484f09ac.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: naveen42x/ped#9

**Comment by Sukkaito** [comment]
Likely to be duplicated with #197

**Comment by Sukkaito** [comment]
This is an intended feature. There will be no fix for this. Thank you for your opinion! 👍
