### ISSUE TITLE
[PE-D][Tester D] Formatting rules should be made more concise

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W13-1/tp#210]
I noted that some commands used [] in the format which was described as 'optional' in the initial input formatting guide. However, an average user in a hurry may forget to read this and type in the values exactly as the format, leading to wasted time. As it is already mentioned next to it that these parameters are optional, I think using a bracket for these parameters is redundant and likely to cause some confusion

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: MayFairMI6/ped#8

**Comment by Sukkaito** [comment]
Maybe NEW USER wouldn't use our CLI while they are busy, so we don't plan to change that. Thank you for your opinion! 👍

**Comment by MayFairMI6** [comment]
Ok no issues, best of luck with your project!
