### ISSUE TITLE
bug: false behavior of edit recipe command

### ISSUE THREAD

**Issue by KSanjith** [AY2425S1-CS2113-W13-1/tp#91]
Step to reproduce:

- Run the program

- Make sure you have at least two recipes with the same name

- Run command: edit e/name_of_duplicate_recipe i/anything s1/anything

Expected results:

- Recipes are sorted by time correctly

Actual results:

- Program hangs

**Comment by 3CCLY** [comment]
Bug has been resolved with duplicate recipes disabled in the addrecipe command, editcommand also only looks at the first recipe in the recipelist matching the name of the recipe to edit now (should be the only recipe of that name).
